name: Add Badges
on:
  push:
    branches:
      - dev
      - dev-*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wow-actions_add-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch
      - name: Show extract_branch info
        env:
          BRANCH: ${{steps.tag_action.outputs.new_tag}}
        run: echo $BRANCH
      - name: Refs
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        run: echo $BRANCH_NAME
      - name: Prints the current branch name
        run: echo "${GITHUB_BRANCH##*/}"
        env:
          GITHUB_BRANCH: ${{ github.ref }}

      - uses: geertmeersman/add-badges@v2.1.12
        env:
          repo_url: ${{ github.event.repository.html_url }}
          repo_name: ${{ github.event.repository.name }}
          repo_owner: ${{ github.event.repository.owner.login }}
          ref: ${{ github.head_ref || github.ref_name }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          badges: |
            [
              {
                "badge": "https://img.shields.io/github/license/${{ env.repo_owner }}/${{ env.repo_name }}",
                "alt": "MIT License",
                "link": "${{ env.repo_url }}/blob/master/LICENSE"
              },
              {
                "badge": "https://img.shields.io/github/issues/${{ env.repo_owner }}/${{ env.repo_name }}",
                "alt": "GitHub issues",
                "link": "https://github.com/${{ env.repo_owner }}/${{ env.repo_name }}/issues"
              },
              {
                "badge": "https://img.shields.io/badge/PRs-Welcome-brightgreen.svg",
                "alt": "PRs Welcome",
                "link": "${{ env.repo_url }}/pulls"
              },
              {
                "badge": "https://img.shields.io/github/actions/workflow/status/${{ env.repo_owner }}/${{ env.repo_name }}/hacs.yml?branch=main&logo=github",
                "alt": "build",
                "link": "${{ env.repo_url }}/actions/workflows/hacs.yml"
              },
              {
                "badge": "https://img.shields.io/github/manifest-json/v/${{ env.repo_owner }}/${{ env.repo_name }}/master?filename=custom_components%2F${{ env.repo_name }}%2Fmanifest.json",
                "alt": "manifest version",
                "link": "${{ env.repo_url }}"
              },
              {
                "badge": "https://img.shields.io/github/v/release/${{ env.repo_owner }}/${{ env.repo_name }}?logo=github",
                "alt": "github release",
                "link": "${{ env.repo_url }}/releases"
              },
              {
                "badge": "https://img.shields.io/github/release-date/${{ env.repo_owner }}/${{ env.repo_name }}",
                "alt": "github release date",
                "link": "${{ env.repo_url }}/releases"
              },
              {
                "badge": "https://img.shields.io/github/last-commit/${{ env.repo_owner }}/${{ env.repo_name }}",
                "alt": "github last-commit",
                "link": "${{ env.repo_url }}/commits"
              },
              {
                "badge": "https://img.shields.io/github/contributors/${{ env.repo_owner }}/${{ env.repo_name }}",
                "alt": "github contributors",
                "link": "${{ env.repo_url }}/graphs/contributors"
              },
              {
                "badge": "https://img.shields.io/badge/Python-FFD43B?logo=python",
                "alt": "Python",
                "link": "${{ env.repo_url }}/search?l=python"
              }
            ]
