name: Validate HACS and with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hassfest_hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: hassfest validation
        uses: home-assistant/actions/hassfest@master
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
