name: Release
on:
  push:
    branches:
      - main
jobs:
  version_upgrade_github_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Version
        run: echo "::set-env name=VERSION::$(cat VERSION)"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ls
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          GITHUB_REPO: ${{ github.event.repository.name }}
        run: |
          ls

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: true
          prerelease: true
#          body: ${{steps.github_release.outputs.changelog}}
